// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urlqurries.sql

package dbservices

import (
	"context"
)

const deleteUrl = `-- name: DeleteUrl :exec
DELETE FROM shortlink
WHERE shortlink =$1
`

func (q *Queries) DeleteUrl(ctx context.Context, shortlink string) error {
	_, err := q.db.Exec(ctx, deleteUrl, shortlink)
	return err
}

const getUrl = `-- name: GetUrl :one
SELECT
  url
FROM
  shortlink
WHERE
  shortlink = $1
`

func (q *Queries) GetUrl(ctx context.Context, shortlink string) (string, error) {
	row := q.db.QueryRow(ctx, getUrl, shortlink)
	var url string
	err := row.Scan(&url)
	return url, err
}

const insertLink = `-- name: InsertLink :exec
INSERT INTO shortlink(
  shortlink,
  url
)
VALUES(
  $1,
  $2
)
RETURNING shortlink, url
`

type InsertLinkParams struct {
	Shortlink string
	Url       string
}

func (q *Queries) InsertLink(ctx context.Context, arg InsertLinkParams) error {
	_, err := q.db.Exec(ctx, insertLink, arg.Shortlink, arg.Url)
	return err
}
